app:
  name: "Book Curator"
  version: "0.1.0"
  debug: false

openai:
  api_key: "${OPENAI_API_KEY}"
  model: "gpt-4o-mini"

database:
  vector_db: "faiss"  # or "chroma"

logging:
  level: "INFO"
  to_file: true
  log_dir: "logs"
